// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChqirP28WRfHMAr86f7tgGL3pMnQR2bc0',
    appId: '1:718109953815:web:62f5e18d51a77a8097b152',
    messagingSenderId: '718109953815',
    projectId: 'jobhub-prm393-g3',
    authDomain: 'jobhub-prm393-g3.firebaseapp.com',
    storageBucket: 'jobhub-prm393-g3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiMria4_NhLEXgxlBoUc39fdjQSnxX07E',
    appId: '1:718109953815:android:2942fd9a90ae208497b152',
    messagingSenderId: '718109953815',
    projectId: 'jobhub-prm393-g3',
    storageBucket: 'jobhub-prm393-g3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiRTRX-5QzcvqX-oKoNVzdPIzcth7Bk80',
    appId: '1:718109953815:ios:a6821884e42aea5d97b152',
    messagingSenderId: '718109953815',
    projectId: 'jobhub-prm393-g3',
    storageBucket: 'jobhub-prm393-g3.firebasestorage.app',
    iosBundleId: 'com.example.jobhubPrm393',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiRTRX-5QzcvqX-oKoNVzdPIzcth7Bk80',
    appId: '1:718109953815:ios:a6821884e42aea5d97b152',
    messagingSenderId: '718109953815',
    projectId: 'jobhub-prm393-g3',
    storageBucket: 'jobhub-prm393-g3.firebasestorage.app',
    iosBundleId: 'com.example.jobhubPrm393',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChqirP28WRfHMAr86f7tgGL3pMnQR2bc0',
    appId: '1:718109953815:web:b03526115d6c161497b152',
    messagingSenderId: '718109953815',
    projectId: 'jobhub-prm393-g3',
    authDomain: 'jobhub-prm393-g3.firebaseapp.com',
    storageBucket: 'jobhub-prm393-g3.firebasestorage.app',
  );
}
